name: Angular Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Install npm dependencies
        run: npm install 
      - name: Build Angular
        run: npm run build --prod
      - name: Setup SSH
        run: |
            mkdir -p ~/.ssh
            ssh-keyscan -H ner.kz >> ~/.ssh/known_hosts
            chmod 600 ~/.ssh/known_hosts
      - name: Deploy to server via SCP
        run: scp -r -o StrictHostKeyChecking=no ./dist/* nurbek@ner.kz:/var/www/html
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
